---
output:
  bookdown::pdf_document2:
    includes:
      in_header: preamble.tex
    toc: FALSE
    highlight: tango
    number_sections: TRUE
    df_print: tibble
    latex_engine: pdflatex
bibliography: [paper.bib, packages.bib]
biblio-style: apalike
urlcolor: black
linkcolor: blue
links-as-notes: true
---

# (APPENDIX) Appendix {-}

# QSA Appendix

```{r, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE, warning = FALSE, message = FALSE, fig.align = "center",
  out.width = "100%", dpi = 300, fig.asp = 0.618, collapse = TRUE
)

devtools::load_all(".")
library(dplyr)
library(ggplot2)
library(patchwork)

uk_qsa_uniform <- readr::read_rds(here::here("data_results", "uk_qsa_uniform.rds"))
uk_qsa_flexible_symmetric <- readr::read_rds(here::here("data_results", "uk_qsa_flexible_symmetric.rds"))
uk_qsa_flexible <- readr::read_rds(here::here("data_results", "uk_qsa_flexible.rds"))

uk_qsa_flexible_symmetric_no_original <- uk_qsa_flexible_symmetric |>
  filter(method == "qsa_flexible_symmetric")

uk_qsa_flexible_no_original <- uk_qsa_flexible |>
  filter(method == "qsa_flexible")

uk_qsa <- bind_rows(uk_qsa_uniform, uk_qsa_flexible_symmetric_no_original, uk_qsa_flexible_no_original)
```

```{r, include=FALSE}
display_table <- function(df, caption, bold_header = TRUE, striped = FALSE) {
  tab <- df |>
    kableExtra::kbl(
      digits = 2, align = "c", booktabs = TRUE, caption = caption
    ) |>
    kableExtra::row_spec(row = 0, bold = bold_header) |>
    kableExtra::kable_styling(position = "center", full_width = FALSE)

  if (striped) {
    tab <- tab |> kableExtra::kable_styling(latex_options = "striped")
  }

  return(tab)
}
```

## QSA across Horizons and Target Types for different Models {-}

```{r fig.cap="Forecasting improvements differ across horizons and target types for model forecasts. Model forecasts only improved across all horizons for the death predictions", fig.height=4, fig.width=4.8, qsa-all-models-horizons-models-target-types, echo=FALSE}
uk_qsa_forecaster <- uk_qsa |>
  filter(model %in% c("EuroCOVIDhub-baseline", "EuroCOVIDhub-ensemble"), target_type == "Cases") # only model forecast

df_hor_forecaster_cases <- eval_methods(uk_qsa_forecaster, summarise_by = "horizon") |>
  select(horizon, qsa_uniform, qsa_flexible_symmetric, qsa_flexible)

p1 <- plot_eval(df_hor_forecaster_cases, base_size = 7) +
  labs(x = NULL, title = "Cases (top) vs. Deaths (bottom)", subtitle = NULL)

uk_qsa_forecaster <- uk_qsa |>
  filter(model %in% c("EuroCOVIDhub-baseline", "EuroCOVIDhub-ensemble"), target_type == "Deaths") # only model forecast

df_hor_forecaster_deaths <- eval_methods(uk_qsa_forecaster, summarise_by = "horizon") |>
  select(horizon, qsa_uniform, qsa_flexible_symmetric, qsa_flexible)

p2 <- plot_eval(df_hor_forecaster_deaths, base_size = 7) +
  labs(x = NULL, title = NULL, subtitle = NULL)

p1 / p2
```

```{r fig.cap="Forecasting improvements differ across horizons and target types for model forecasts. Human forecasts are primarily improved for cases and the horizons of 3 and 4 weeks ahead. For deaths \\texttt{qsa\\_flexible} worsens the score", fig.height=4, fig.width=4.8, qsa-all-models-horizons-humans-target-types, echo=FALSE}
uk_qsa_forecaster <- uk_qsa |>
  filter(model %in% c("epiforecasts-EpiExpert", "epiforecasts-EpiExpert_Rt", "epiforecasts-EpiExpert_direct", "seabbs"), target_type == "Cases") # only human forecast

df_hor_forecaster_cases <- eval_methods(uk_qsa_forecaster, summarise_by = "horizon") |>
  select(horizon, qsa_uniform, qsa_flexible_symmetric, qsa_flexible)

p1 <- plot_eval(df_hor_forecaster_cases, base_size = 7) +
  labs(x = NULL, title = "Cases (top) vs. Deaths (bottom)", subtitle = NULL)

uk_qsa_forecaster <- uk_qsa |>
  filter(model %in% c("epiforecasts-EpiExpert", "epiforecasts-EpiExpert_Rt", "epiforecasts-EpiExpert_direct", "seabbs"), target_type == "Deaths") # only human forecast

df_hor_forecaster_deaths <- eval_methods(uk_qsa_forecaster, summarise_by = "horizon") |>
  select(horizon, qsa_uniform, qsa_flexible_symmetric, qsa_flexible)

p2 <- plot_eval(df_hor_forecaster_deaths, base_size = 7) +
  labs(x = NULL, title = NULL, subtitle = NULL)

p1 / p2
```
