---
output:
  bookdown::pdf_document2:
    includes:
      in_header: preamble.tex
      before_body: title.tex
    toc: FALSE
    highlight: tango
    number_sections: TRUE
    df_print: tibble
    latex_engine: pdflatex
bibliography: [paper.bib, packages.bib]
biblio-style: apalike
urlcolor: black
linkcolor: blue
links-as-notes: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE, warning = FALSE, message = FALSE, fig.align = "center",
  out.width = "100%", dpi = 300, fig.asp = 0.618, collapse = TRUE
)
```

```{r include=FALSE}
# creates bibliography file for R packages
knitr::write_bib(
  c(
    "base", "dplyr", "doParallel", "forcats", "foreach", "ggplot2", "lubridate", "nloptr",
    "rlang", "scales", "scoringutils", "stats", "stringr", "tidyr", "tidyselect", "here",
    "kableExtra", "knitr", "readr", "rmarkdown", "testthat"
  ),
  file = here::here("term_paper", "packages.bib")
)
```

```{r child=here::here("term_paper", "0_introduction.Rmd")}
```


```{r child=here::here("term_paper", "1_data_package.Rmd")}
```


```{r child=here::here("term_paper", "2_cqr_1.Rmd")}
```

```{r child=here::here("term_paper", "2_cqr_2.Rmd")}
```

```{r child=here::here("term_paper", "2_cqr_3.Rmd")}
```


```{r child=here::here("term_paper", "3_qsa_1.Rmd")}
```

```{r child=here::here("term_paper", "3_qsa_2.Rmd")}
```


```{r child=here::here("term_paper", "4_comparison.Rmd")}
```


```{r child=here::here("term_paper", "5_conclusion.Rmd")}
```

<!-- 
\newpage

```{r child=here::here("term_paper", "6_appendix.Rmd")}
```
-->
 
\newpage

# References {-}
