---
title: "Examples of `add_ensemble()` Function"
author: "Joel Beck"
output:
  bookdown::pdf_document2:
    highlight: tango
    toc: FALSE
    number_sections: FALSE
    df_print: tibble
    latex_engine: pdflatex
    keep_tex: FALSE
  bookdown::html_document2:
    theme: flatly
    highlight: pygments
    toc: TRUE
    toc_float: TRUE
    number_sections: FALSE
    df_print: tibble
urlcolor: blue
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE, warning = FALSE, message = FALSE, fig.align = "center",
  out.width = "100%", dpi = 300, fig.asp = 0.618, collapse = TRUE
)
```

```{r}
devtools::load_all()
uk_cqr_qsa <- readr::read_rds(
  here::here("data_results", "uk_cqr_qsa_uniform.rds")
)

models <- "epiforecasts-EpiExpert"
df_combined <- uk_cqr_qsa |> dplyr::filter(model == models)
```

# Same weight for all quantiles

```{r}
add_ensemble(df_combined, verbose = TRUE, per_quantile_weights = FALSE) |>
  extract_validation_set() |>
  scoringutils::score() |>
  scoringutils::summarise_scores(by = c("method")) |>
  dplyr::select(method:interval_score)
```

# Separate weights for each quantiles

```{r}
add_ensemble(df_combined, verbose = TRUE, per_quantile_weights = TRUE) |>
  extract_validation_set() |>
  scoringutils::score() |>
  scoringutils::summarise_scores(by = c("method")) |>
  dplyr::select(method:interval_score)
```
