---
title: "Detailed UK-Data Analysis"
author: "Joel Beck"
output:
  bookdown::pdf_document2:
    highlight: tango
    toc: FALSE
    number_sections: FALSE
    df_print: tibble
    latex_engine: pdflatex
    keep_tex: FALSE
  bookdown::html_document2:
    theme: flatly
    highlight: pygments
    toc: TRUE
    toc_float: TRUE
    number_sections: FALSE
    df_print: tibble
urlcolor: blue
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE, warning = FALSE, message = FALSE, fig.align = "center",
  out.width = "100%", dpi = 300, fig.asp = 0.618, collapse = TRUE
)
```

```{r}
devtools::load_all()
df_combined <- readr::read_rds(here::here("data_results", "uk_cqr.rds"))
```

## By single category

```{r}
# TODO: Add unit tests that attribute summarise_by is set correctly by eval_cqr()

eval_cqr(df_combined, summarise_by = "model")
eval_cqr(df_combined, summarise_by = "target_type")
eval_cqr(df_combined, summarise_by = "horizon")
df_eval <- eval_cqr(df_combined, summarise_by = "quantile")
attributes(df_eval)
# TODO: Fix x-label
plot_eval(df_eval)
```

## By combination of two categories

```{r}
eval_cqr(df_combined, summarise_by = c("model", "target_type"))
eval_cqr(df_combined, summarise_by = c("model", "horizon"))
df_eval <- eval_cqr(df_combined, summarise_by = c("horizon", "target_type"))
attributes(df_eval)
plot_eval(df_eval)
```

## Add marginal relative changes

```{r}
# not really informative, since margins are dominated by category with largest
# values, here "Cases"
# => these margins are almost identical to one row / column of table

# sorted by increasing relative changes
eval_cqr(df_combined, summarise_by = "model")
eval_cqr(df_combined, summarise_by = "target_type")

# not sorted by relative changes
df_eval <- eval_cqr(
  df_combined,
  summarise_by = c("model", "target_type"), margins = TRUE
)
attributes(df_eval)
plot_eval(df_eval)
```


## Add 'average' (geometric mean) relative changes of rows and columns

```{r}
eval_cqr(
  df_combined,
  summarise_by = c("horizon", "target_type"), row_averages = TRUE
)

eval_cqr(
  df_combined,
  summarise_by = c("horizon", "target_type"), col_averages = TRUE
)

df_eval <- eval_cqr(
  df_combined,
  summarise_by = c("horizon", "target_type"), row_averages = TRUE,
  col_averages = TRUE
)
attributes(df_eval)
# TODO: Fix order of x labels
plot_eval(df_eval)
```
