---
title: "UK Data Exploration"
author: "Joel Beck"
output:
  bookdown::html_document2:
    theme: flatly
    highlight: pygments  # kate
    toc: TRUE
    toc_float: TRUE
    toc_depth: 2
    number_sections: FALSE
    df_print: tibble
  bookdown::pdf_document2:
    highlight: tango  # pygments
    toc: FALSE
    number_sections: FALSE
    df_print: tibble
    latex_engine: pdflatex
    keep_tex: FALSE
urlcolor: blue
---

```{r knitr-opts, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE, warning = FALSE, message = FALSE, fig.align = "center",
  out.width = "100%", dpi = 300, fig.asp = 0.618, collapse = TRUE
)
```

```{r libraries}
# temporary and not recommended way, library(postforecasts) imports only functions with @export tag 
# => requires more complete documentation
devtools::load_all(".")

library(scoringutils)
library(dplyr)
```

# Original Dataframe

```{r}
df <- read.csv(here::here("data", "full-data-uk-challenge.csv"))
```

# Plot Original Predictions

```{r}
model <- "epiforecasts-EpiExpert"
location <- "GB"
plot_quantiles(df, model, location, quantiles = c(0.01, 0.05, 0.25, 0.5, 0.75, 0.95, 0.99))
```

# Update Predictions

```{r}
# Option 1 (new)
df_list <- update_predictions(df, methods = "cqr", model, location, cv_init_training = 3, filter_original = TRUE)
df_combined_1 <- collect_predictions(df_list)
```

```{r}
# Option 2 (old)
df_updated <- update_predictions(df, methods = "cqr", model, location, cv_init_training = 3)
preprocessed_list <- preprocess_df(df, model)
df_combined_2 <- collect_predictions(original = preprocessed_list$df, cqr = df_updated)
```

```{r}
# same behaviour for single method
all(df_combined_1 == df_combined_2)
```


# Numerical Analysis

```{r}
df_combined_1 |>
  filter_models(model) |>
  filter_locations(location) |> 
  eval_forecasts(summarise_by = c("method", "model", "target_type")) |> 
  arrange(target_type, desc(method))
```

# Graphical Analysis

## for given `model`, `location`, `target_type`, `quantile` and `horizon`

```{r}
plot_intervals(df_combined_1, model, location, target_type = "Cases", quantile = 0.05, horizon = 1)
```

## for given `model`, `location` and `quantile` and different `horizons`

```{r}
plot_intervals_grid(df_combined_1, model, facet_by = "horizon", highlight_cv = TRUE)
```

## for given `model`, `location` and `horizon` and different `quantiles`

```{r}
plot_intervals_grid(df_combined_1, model, facet_by = "quantile", highlight_cv = TRUE)
```
