---
title: "Examples of `add_ensemble()` Function"
author: "Joel Beck"
output:
  bookdown::pdf_document2:
    highlight: tango
    toc: FALSE
    number_sections: FALSE
    df_print: tibble
    latex_engine: pdflatex
    keep_tex: FALSE
  bookdown::html_document2:
    theme: flatly
    highlight: pygments
    toc: TRUE
    toc_float: TRUE
    number_sections: FALSE
    df_print: tibble
urlcolor: blue
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE, warning = FALSE, message = FALSE, fig.align = "center",
  out.width = "100%", dpi = 300, fig.asp = 0.618, collapse = TRUE
)
```

```{r}
devtools::load_all()
```

# UK Data

```{r}
df_combined <- readr::read_rds(here::here("data_results", "uk_cqr3.rds"))
df_subset <- df_combined |> dplyr::filter(model == unique(df_combined$model)[1])

df_ensemble <- add_ensemble(df_subset, train_val_split = FALSE, verbose = TRUE, max_iter = 1e5)
attr(df_ensemble, which = "weights")
```

# Interval Scores on Training Set

```{r}
df_ensemble <- readr::read_rds(here::here("data_results", "uk_cqr3_ensemble.rds"))

df_ensemble |>
  scoringutils::score() |>
  scoringutils::summarise_scores(by = c("method")) |>
  # scoringutils::summarise_scores(
  #   by = c("method", "model", "horizon", "target_type", "quantile")) |>
  dplyr::select(method:interval_score)
# dplyr::arrange(model, horizon, target_type, quantile) |>
# dplyr::mutate(interval_score = round(interval_score, 3)) |>
# tidyr::pivot_wider(names_from = method, values_from = interval_score) |>
# dplyr::filter(ensemble > cqr_asymmetric)
```

# Interval Scores on Validation Set

```{r}
df_ensemble |>
  extract_validation_set() |>
  scoringutils::score() |>
  scoringutils::summarise_scores(by = c("method")) |>
  dplyr::select(method:dispersion) |>
  dplyr::mutate(interval_score = round(interval_score, 3)) |>
  print(n = Inf)
```

# Debugging

```{r}
df_combined <- readr::read_rds(here::here("data_results", "uk_cqr3.rds"))
l <- "GB"
m <- unique(df_combined$model)[1]
t <- "Cases"
h <- 1
q <- 0.05

ensemble_df <- df_combined |> dplyr::filter(.data$method == "original")
ensemble_df["method"] <- "ensemble"

methods <- unique(df_combined$method)
methods <- methods[methods != "original"]

df_subset <- get_pairs_subset(df_combined, l, m, t, h, q)
score_subset <- score_pairs_subset(df_subset, train_val_split = FALSE)
wide_score_subset <- pivot_score_subset(score_subset)

score_matrix <- get_score_matrix(wide_score_subset, methods, q)
weights <- compute_weights(score_matrix, max_iter = 1e5, print_level = 3)

quantiles_low_matrix <- get_quantiles_low_matrix(df_subset, q, methods)
quantiles_high_matrix <- get_quantiles_high_matrix(df_subset, q, methods)

quantiles_low_ensemble <- as.numeric(quantiles_low_matrix %*% weights)
quantiles_high_ensemble <- as.numeric(quantiles_high_matrix %*% weights)

ensemble_df <- assign_quantiles_low(ensemble_df, quantiles_low_ensemble, l, m, t, h, q)
ensemble_df <- assign_quantiles_high(ensemble_df, quantiles_high_ensemble, l, m, t, h, q)

ensemble_df |>
  dplyr::filter(
    method == "ensemble", location == l, model == m, target_type == t,
    horizon == h, quantile == q
  ) |>
  dplyr::pull(prediction)

ensemble_df |>
  dplyr::filter(
    method == "ensemble", location == l, model == m, target_type == t,
    horizon == h, quantile == 1 - q
  ) |>
  dplyr::pull(prediction)

df_ensemble |>
  dplyr::filter(
    method == "ensemble", location == l, model == m, target_type == t,
    horizon == h, quantile == q
  ) |>
  dplyr::pull(prediction)

df_ensemble |>
  dplyr::filter(
    method == "ensemble", location == l, model == m, target_type == t,
    horizon == h, quantile == 1 - q
  ) |>
  dplyr::pull(prediction)
```


```{r}
# for (l in unique(df_combined$location)) {
#   for (m in unique(df_combined$model)) {
#     for (t in unique(df_combined$target_type)) {
for (h in unique(df_combined$horizon)) {
  for (q in quantiles) {
    df_subset <- get_pairs_subset(df_combined, l, m, t, h, q)

    true_values <- get_true_values(df_subset, methods)
    quantiles_low_matrix <- get_quantiles_low_matrix(df_subset, q, methods)
    quantiles_high_matrix <- get_quantiles_high_matrix(df_subset, q, methods)

    weights <- compute_weights(
      q, true_values, quantiles_low_matrix, quantiles_high_matrix,
      max_iter = 1e5, print_level = 0
    )

    quantiles_low_ensemble <- as.numeric(quantiles_low_matrix %*% weights)
    quantiles_high_ensemble <- as.numeric(quantiles_high_matrix %*% weights)

    quantiles <- unique(df_combined$quantile)
    quantiles <- quantiles[quantiles < 0.5]

    wis_cqr <- compute_wis(q, true_values, quantiles_low_matrix[, 1], quantiles_high_matrix[, 1])
    wis_asym <- compute_wis(q, true_values, quantiles_low_matrix[, 2], quantiles_high_matrix[, 2])
    wis_mult <- compute_wis(q, true_values, quantiles_low_matrix[, 3], quantiles_high_matrix[, 3])
    wis_ens <- compute_wis(q, true_values, quantiles_low_ensemble, quantiles_high_ensemble)

    if (wis_ens != min(wis_cqr, wis_asym, wis_mult, wis_ens)) {
      cat(
        # "Mistake: \n",
        # "Model = ", m, "\n",
        # "Target Type = ", t, "\n",
        "Horizon = ", h, "\n",
        "Quantile = ", q, "\n",
        "\n",
        sep = ""
      )
      cat(
        "CQR = ", wis_cqr, "\n",
        "Asymmetric = ", wis_asym, "\n",
        "Multiplicative = ", wis_mult, "\n",
        "Ensemble = ", wis_ens, "\n",
        "Weights = ", paste(round(weights, 3), collapse = ", "), "\n\n",
        sep = ""
      )
    }
  }
}
#     }
#   }
# }
```


# Analysis

```{r}
df_ensemble <- readr::read_rds(here::here("data_results", "uk_cqr3_ensemble.rds"))
```

```{r}
l <- "GB"
m <- unique(df_combined$model)[1]
t <- "Cases"
h <- 1
q <- 0.1

df_weights <- attr(df_ensemble, "weights")
df_weights |>
  dplyr::filter(model == m, location == l, target_type == t, quantile == q, horizon == h) |>
  purrr::pluck("weights", 1)

plot_intervals(
  df_ensemble,
  model = m, location = l, target_type = t, quantile = q, horizon = h
)
```
